# Generated by Django 5.2.15 on 2026-06-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trafficrecord',
            new_name='traffic_tra_zone_c11587_idx',
            old_name='traffic_tra_zone_318867_idx',
        ),
        migrations.AddField(
            model_name='trafficrecord',
            name='source',
            field=models.CharField(default='desconocido', max_length=50),
        ),
    ]
